export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const MOVIE_REQUEST = 'MOVIE_REQUEST';
export const MOVIE_SUCCESS = 'MOVIE_SUCCESS';
export const MOVIE_FAILURE = 'MOVIE_FAILURE';
export const MOVIE_REMOVE = 'MOVIE_REMOVE';

export const SUGGESTS_REQUEST = 'SUGGESTS_REQUEST';
export const SUGGESTS_SUCCESS = 'SUGGESTS_SUCCESS';
export const SUGGESTS_FAILURE = 'SUGGESTS_FAILURE';
